//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Scenes/ARSampleActoions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ARSampleActoions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ARSampleActoions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ARSampleActoions"",
    ""maps"": [
        {
            ""name"": ""ARSampleControls"",
            ""id"": ""3943ba85-eba5-49b9-aa71-a781c6ad337d"",
            ""actions"": [
                {
                    ""name"": ""ScreenTouch"",
                    ""type"": ""Value"",
                    ""id"": ""3de1963b-3d75-420f-8c02-e2e86f8c33db"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bca7d246-771a-45c1-b27d-17b07bdf163a"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScreenTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ARSampleControls
        m_ARSampleControls = asset.FindActionMap("ARSampleControls", throwIfNotFound: true);
        m_ARSampleControls_ScreenTouch = m_ARSampleControls.FindAction("ScreenTouch", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ARSampleControls
    private readonly InputActionMap m_ARSampleControls;
    private List<IARSampleControlsActions> m_ARSampleControlsActionsCallbackInterfaces = new List<IARSampleControlsActions>();
    private readonly InputAction m_ARSampleControls_ScreenTouch;
    public struct ARSampleControlsActions
    {
        private @ARSampleActoions m_Wrapper;
        public ARSampleControlsActions(@ARSampleActoions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ScreenTouch => m_Wrapper.m_ARSampleControls_ScreenTouch;
        public InputActionMap Get() { return m_Wrapper.m_ARSampleControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ARSampleControlsActions set) { return set.Get(); }
        public void AddCallbacks(IARSampleControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_ARSampleControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ARSampleControlsActionsCallbackInterfaces.Add(instance);
            @ScreenTouch.started += instance.OnScreenTouch;
            @ScreenTouch.performed += instance.OnScreenTouch;
            @ScreenTouch.canceled += instance.OnScreenTouch;
        }

        private void UnregisterCallbacks(IARSampleControlsActions instance)
        {
            @ScreenTouch.started -= instance.OnScreenTouch;
            @ScreenTouch.performed -= instance.OnScreenTouch;
            @ScreenTouch.canceled -= instance.OnScreenTouch;
        }

        public void RemoveCallbacks(IARSampleControlsActions instance)
        {
            if (m_Wrapper.m_ARSampleControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IARSampleControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_ARSampleControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ARSampleControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ARSampleControlsActions @ARSampleControls => new ARSampleControlsActions(this);
    public interface IARSampleControlsActions
    {
        void OnScreenTouch(InputAction.CallbackContext context);
    }
}
